"""
LOVE Credential Setup Wizard

Run this once to configure all your accounts and integrations.
Guides you through each service with clear instructions.

Usage:
  python setup_credentials.py
"""

import os
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ENV_FILE = PROJECT_ROOT / ".env"
SETTINGS_FILE = PROJECT_ROOT / "settings.yaml"


def read_env() -> dict:
    env = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def write_env(env: dict):
    lines = ["# Project LOVE — Environment Variables", "# Generated by setup_credentials.py", ""]
    # Keep comments for sections
    sections = {
        "OLLAMA_BASE_URL": "# === LLM (Ollama) ===",
        "GOOGLE_CREDENTIALS_PATH": "# === Google (Calendar, Gmail, Drive) ===",
        "MICROSOFT_CLIENT_ID": "# === Microsoft 365 (Outlook, Teams, OneDrive) ===",
        "PHONE_DEVICE_ID": "# === Phone (KDE Connect) ===",
        "GITHUB_TOKEN": "# === GitHub ===",
        "FINANCE_WATCHLIST": "# === Finance / Markets ===",
        "CHROME_DEBUG_PORT": "# === Browser Monitor ===",
        "TELEGRAM_BOT_TOKEN": "# === Telegram Bot ===",
    }
    added_sections = set()
    for key, val in env.items():
        for sec_key, sec_comment in sections.items():
            if key == sec_key and sec_key not in added_sections:
                lines.append("")
                lines.append(sec_comment)
                added_sections.add(sec_key)
                break
        lines.append(f"{key}={val}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"  Saved to {ENV_FILE}")


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    if default:
        display = f"[{default[:4]}****]" if secret and default else f"[{default}]"
        prompt = f"{prompt} {display}: "
    else:
        prompt = f"{prompt}: "
    try:
        val = input(prompt).strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default


def section(title: str):
    print(f"\n{'='*50}")
    print(f"  {title}")
    print(f"{'='*50}")


def setup_google(env: dict) -> dict:
    section("Google (Calendar, Gmail, Drive)")
    print("  Needed for: Meeting awareness, email summaries, Drive file context")
    print("  Setup: https://console.cloud.google.com")
    print("  1. Create project → Enable Calendar + Gmail + Drive APIs")
    print("  2. Create OAuth2 Desktop credentials")
    print("  3. Download as credentials.json → place in project root")
    print()
    has_creds = Path(PROJECT_ROOT / "credentials.json").exists()
    if has_creds:
        print("  credentials.json found!")
    else:
        creds_path = ask("  Path to credentials.json (or press Enter to skip)", "")
        if creds_path and Path(creds_path).exists():
            import shutil
            shutil.copy(creds_path, PROJECT_ROOT / "credentials.json")
            print("  Copied to project root.")
    env["GOOGLE_CREDENTIALS_PATH"] = "./credentials.json"
    env["GOOGLE_TOKEN_PATH"] = "./data/google_token.json"
    return env


def setup_microsoft(env: dict) -> dict:
    section("Microsoft 365 (Outlook, Teams, OneDrive)")
    print("  Needed for: Email, meetings, Teams messages, OneDrive files")
    print("  Setup: https://portal.azure.com → App registrations")
    print("  1. New registration → 'LOVE Assistant'")
    print("  2. API Permissions: Mail.Read, Calendars.Read, Chat.Read, Files.Read.All")
    print("  3. Authentication → Mobile/Desktop → urn:ietf:wg:oauth:2.0:oob")
    print("  4. Copy Application (client) ID")
    print()
    client_id = ask("  Microsoft App Client ID (or Enter to skip)", env.get("MICROSOFT_CLIENT_ID", ""))
    if client_id:
        env["MICROSOFT_CLIENT_ID"] = client_id
        tenant = ask("  Tenant ID (or 'common' for personal accounts)", env.get("MICROSOFT_TENANT_ID", "common"))
        env["MICROSOFT_TENANT_ID"] = tenant or "common"
        print("  After saving, run: POST http://localhost:8000/integrations/microsoft/auth")
        print("  Follow the device code flow to authenticate.")
    return env


def setup_github(env: dict) -> dict:
    section("GitHub")
    print("  Needed for: PR alerts, commit activity, issue tracking")
    print("  Setup: https://github.com/settings/tokens → New classic token")
    print("  Scopes needed: repo, notifications")
    print()
    token = ask("  GitHub Personal Access Token (or Enter to skip)", env.get("GITHUB_TOKEN", ""), secret=True)
    if token:
        env["GITHUB_TOKEN"] = token
        username = ask("  GitHub username", env.get("GITHUB_USERNAME", ""))
        if username:
            env["GITHUB_USERNAME"] = username
    return env


def setup_finance(env: dict) -> dict:
    section("Finance & Markets")
    print("  Crypto prices via Binance public API (no key needed)")
    print("  Stock prices via Yahoo Finance (no key needed)")
    print()
    crypto = ask("  Crypto watchlist (comma-separated)", env.get("FINANCE_WATCHLIST", "BTCUSDT,ETHUSDT,SOLUSDT"))
    if crypto:
        env["FINANCE_WATCHLIST"] = crypto
    stocks = ask("  Stock watchlist (comma-separated)", env.get("STOCK_WATCHLIST", "AAPL,NVDA,TSLA"))
    if stocks:
        env["STOCK_WATCHLIST"] = stocks
    threshold = ask("  Price alert threshold (e.g. 0.05 = 5% move)", env.get("PRICE_ALERT_THRESHOLD", "0.05"))
    if threshold:
        env["PRICE_ALERT_THRESHOLD"] = threshold
    return env


def setup_phone(env: dict) -> dict:
    section("Phone Bridge (KDE Connect / iOS)")
    print("  Android: Install KDE Connect on phone + PC")
    print("    https://kdeconnect.kde.org/")
    print("    Pair on same WiFi → auto-discovers")
    print()
    print("  iOS: Use Shortcuts app to POST to http://YOUR_PC_IP:8000/integrations/phone/update")
    print("    Include JSON: {battery, location_label, missed_calls}")
    print()
    device_id = ask("  KDE Connect device name (run 'kdeconnect-cli -l' to find it)", env.get("PHONE_DEVICE_ID", ""))
    if device_id:
        env["PHONE_DEVICE_ID"] = device_id
    return env


def setup_telegram(env: dict) -> dict:
    section("Telegram Bot (optional)")
    print("  LOVE can send you Telegram messages proactively")
    print("  Setup: Message @BotFather on Telegram → /newbot")
    print()
    token = ask("  Telegram Bot Token (or Enter to skip)", env.get("TELEGRAM_BOT_TOKEN", ""), secret=True)
    if token:
        env["TELEGRAM_BOT_TOKEN"] = token
        chat_id = ask("  Your Telegram Chat ID (message @userinfobot to find out)", env.get("TELEGRAM_CHAT_ID", ""))
        if chat_id:
            env["TELEGRAM_CHAT_ID"] = chat_id
    return env


def setup_browser(env: dict) -> dict:
    section("Browser Intelligence")
    print("  LOVE can read your active browser tab for context")
    print("  Chrome/Edge: Add --remote-debugging-port=9222 to browser shortcut target")
    print("  Or just use the window-title fallback (no setup needed)")
    print()
    port = ask("  Chrome remote debugging port", env.get("CHROME_DEBUG_PORT", "9222"))
    env["CHROME_DEBUG_PORT"] = port
    return env


def main():
    print("=" * 60)
    print("  LOVE Intelligence Setup Wizard")
    print("  Configure all your accounts and devices")
    print("=" * 60)
    print()
    print("This wizard will guide you through setting up each integration.")
    print("Press Enter to skip any service you don't want to connect.")
    print()

    env = read_env()

    # Preserve existing LLM settings
    if "OLLAMA_BASE_URL" not in env:
        env["OLLAMA_BASE_URL"] = "http://127.0.0.1:11434"
    if "REASONING_MODEL" not in env:
        env["REASONING_MODEL"] = "deepseek-r1:7b"
    if "CODING_MODEL" not in env:
        env["CODING_MODEL"] = "qwen2.5-coder:7b"
    if "EMBED_MODEL" not in env:
        env["EMBED_MODEL"] = "nomic-embed-text"

    services = [
        ("Google (Calendar, Gmail, Drive)", setup_google),
        ("Microsoft 365 (Outlook, Teams)", setup_microsoft),
        ("GitHub", setup_github),
        ("Finance & Markets", setup_finance),
        ("Phone (KDE Connect)", setup_phone),
        ("Telegram Bot", setup_telegram),
        ("Browser Intelligence", setup_browser),
    ]

    for name, fn in services:
        try:
            answer = ask(f"\nSetup {name}? (y/N)", "n")
            if answer.lower() in ("y", "yes"):
                env = fn(env)
        except Exception as e:
            print(f"  Error in {name} setup: {e}")

    print("\n" + "=" * 60)
    write_env(env)
    print("\nSetup complete!")
    print()
    print("Next steps:")
    print("  1. Start LOVE: uvicorn api.main:app --reload")
    print("  2. Authorize Google: POST http://localhost:8000/integrations/google/auth")
    print("  3. Authorize Microsoft: POST http://localhost:8000/integrations/microsoft/auth")
    print("  4. Open UI: http://localhost:8000")
    print()


if __name__ == "__main__":
    main()
