"""
LOVE Autonomous Trading Engine

Generates, tests, and evolves trading strategies automatically.
- Uses LLM to invent new strategy ideas based on market conditions
- Auto-backtests every generated strategy
- Paper-trades the best performers
- Evolves strategies: mutates params, combines top performers
- Pushes insights and results to user proactively

Runs in a background thread, completely autonomous.
"""

import json
import os
import random
import re
import threading
import time
import urllib.request
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from core.execution_guard import log_error

# Wave 25+ Quantitative Modules
try:
    from core.quantitative_signals import get_quant_signals
    QUANT_AVAILABLE = True
except ImportError:
    QUANT_AVAILABLE = False
try:
    from core.risk_manager import get_risk_manager
    RISK_AVAILABLE = True
except ImportError:
    RISK_AVAILABLE = False
try:
    from core.market_regime_detector import get_regime_detector
    REGIME_AVAILABLE = True
except ImportError:
    REGIME_AVAILABLE = False
try:
    from core.sentiment_analyzer import get_sentiment_analyzer
    SENTIMENT_AVAILABLE = True
except ImportError:
    SENTIMENT_AVAILABLE = False

# Neural Bus
try:
    from core.neural_bus import get_neural_bus, EventPriority
    NEURAL_BUS_AVAILABLE = True
except ImportError:
    NEURAL_BUS_AVAILABLE = False

# Proactive Push
try:
    from core.proactive_push import get_push_engine
    PUSH_AVAILABLE = True
except ImportError:
    PUSH_AVAILABLE = False

DATA_DIR = Path(__file__).parent.parent / "data"
GENERATED_STRATEGIES_DB = DATA_DIR / "generated_strategies.json"
STRATEGY_EVOLUTION_LOG = DATA_DIR / "strategy_evolution.jsonl"
AUTO_TRADE_LOG = DATA_DIR / "auto_trades.jsonl"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Config
AUTO_GENERATE_INTERVAL = int(os.getenv("ATE_GENERATE_INTERVAL_MINUTES", "60"))
AUTO_PAPER_TRADE_INTERVAL = int(os.getenv("ATE_PAPER_TRADE_INTERVAL_MINUTES", "15"))
MAX_GENERATED_STRATEGIES = int(os.getenv("ATE_MAX_STRATEGIES", "20"))
TOP_STRATEGY_COUNT = int(os.getenv("ATE_TOP_COUNT", "3"))


class GeneratedStrategy:
    """A strategy generated by the LLM with metadata and performance tracking."""

    def __init__(self, name: str, description: str, logic_type: str, params: Dict,
                 code: str = "", generation_prompt: str = ""):
        self.id = f"gen_{int(time.time())}_{random.randint(1000, 9999)}"
        self.name = name
        self.description = description
        self.logic_type = logic_type  # e.g. "momentum", "mean_reversion", "breakout"
        self.params = params
        self.code = code
        self.generation_prompt = generation_prompt
        self.created_at = datetime.now().isoformat()
        self.backtests: List[Dict] = []
        self.paper_trades: List[Dict] = []
        self.status = "generated"  # generated -> backtested -> active -> retired
        self.score = 0.0  # composite score
        self.best_return = 0.0
        self.win_rate = 0.0
        self.total_trades = 0
        self.sharpe_estimate = 0.0

    def to_dict(self) -> Dict:
        return {
            "id": self.id, "name": self.name, "description": self.description,
            "logic_type": self.logic_type, "params": self.params, "code": self.code,
            "generation_prompt": self.generation_prompt, "created_at": self.created_at,
            "backtests": self.backtests, "paper_trades": self.paper_trades,
            "status": self.status, "score": self.score, "best_return": self.best_return,
            "win_rate": self.win_rate, "total_trades": self.total_trades,
            "sharpe_estimate": self.sharpe_estimate,
        }

    @classmethod
    def from_dict(cls, data: Dict) -> "GeneratedStrategy":
        s = cls(data["name"], data["description"], data.get("logic_type", "unknown"),
                data.get("params", {}), data.get("code", ""), data.get("generation_prompt", ""))
        s.id = data["id"]
        s.created_at = data.get("created_at", datetime.now().isoformat())
        s.backtests = data.get("backtests", [])
        s.paper_trades = data.get("paper_trades", [])
        s.status = data.get("status", "generated")
        s.score = data.get("score", 0.0)
        s.best_return = data.get("best_return", 0.0)
        s.win_rate = data.get("win_rate", 0.0)
        s.total_trades = data.get("total_trades", 0)
        s.sharpe_estimate = data.get("sharpe_estimate", 0.0)
        return s


class StrategyExecutor:
    """Executes generated strategy code safely."""

    def __init__(self, strategy: GeneratedStrategy):
        self.strategy = strategy
        self._compiled = None
        self._state = {}

    def compile(self) -> bool:
        """Compile the generated strategy code."""
        if not self.strategy.code:
            return False
        try:
            # Wrap in a function that takes candles and returns signal
            code = self.strategy.code
            # If code is just logic, wrap it
            if "def on_data" not in code:
                code = f"""
_state = {{}}
{code}
def on_data(candles):
    import statistics
    closes = [float(c[4]) for c in candles]
    if len(closes) < 10:
        return "HOLD"
    return _strategy_logic(closes, _state)
"""
            # Compile safely
            self._compiled = compile(code, f"<strategy_{self.strategy.id}>", "exec")
            return True
        except Exception as e:
            print(f"[ATE] Strategy compilation failed for {self.strategy.id}: {e}")
            return False

    def run(self, candles: List[List]) -> str:
        """Run the strategy on candle data."""
        if self._compiled is None and not self.compile():
            return "HOLD"
        try:
            # Normalize params: convert string numbers to float/int,
            # and cast floats that are whole numbers back to int so list indexing works.
            raw_params = self.strategy.params or {}
            norm_params: Dict[str, Any] = {}
            for k, v in raw_params.items():
                if isinstance(v, str):
                    try:
                        if "." in v:
                            norm_params[k] = float(v)
                        else:
                            norm_params[k] = int(v)
                    except ValueError:
                        norm_params[k] = v
                elif isinstance(v, float) and v.is_integer():
                    norm_params[k] = int(v)
                else:
                    norm_params[k] = v

            def get_param(key: str, default=0.0):
                return norm_params.get(key, default)

            def get_int_param(key: str, default: int = 10) -> int:
                """Return param as int — safe for list indexing."""
                v = norm_params.get(key, default)
                try:
                    return int(float(v))
                except (TypeError, ValueError):
                    return int(default)

            def get_float_param(key: str, default: float = 0.0) -> float:
                """Return param as float."""
                v = norm_params.get(key, default)
                try:
                    return float(v)
                except (TypeError, ValueError):
                    return float(default)

            local_ns = {
                "candles": candles,
                "statistics": __import__("statistics"),
            }
            # Build globals for exec: include helpers AND inject each param
            # as a bare-name global so poorly-generated strategies that reference
            # param names directly (e.g., `trend_line_length`) still work.
            exec_globals = {
                "__builtins__": __builtins__,
                "params": norm_params,
                "get_param": get_param,
                "get_int_param": get_int_param,
                "get_float_param": get_float_param,
            }
            for k, v in norm_params.items():
                if k not in exec_globals:
                    exec_globals[k] = v
            exec(self._compiled, exec_globals, local_ns)
            on_data_fn = local_ns.get("on_data")
            if on_data_fn:
                return on_data_fn(candles)
            return "HOLD"
        except Exception as e:
            print(f"[ATE] Strategy execution error: {e}")
            return "HOLD"


class AutonomousTradingEngine:
    """Generates, tests, and evolves trading strategies autonomously."""

    _instance = None
    _lock = threading.Lock()

    def __init__(self):
        self._strategies: deque = deque(maxlen=MAX_GENERATED_STRATEGIES)
        self._running = False
        self._threads: List[threading.Thread] = []
        self._last_generate_time = 0.0
        self._last_paper_trade_time = 0.0
        self._auto_collection_last_run = 0.0
        self._market_cache: Dict[str, Any] = {}
        self._auto_trade_enabled = True  # Can be toggled from UI
        # Quantitative module hooks
        self.quant_engine = get_quant_signals() if QUANT_AVAILABLE else None
        self.risk_engine = get_risk_manager() if RISK_AVAILABLE else None
        self.regime_engine = get_regime_detector() if REGIME_AVAILABLE else None
        self.sentiment_engine = get_sentiment_analyzer() if SENTIMENT_AVAILABLE else None
        self._load_strategies()

    @classmethod
    def get_instance(cls) -> "AutonomousTradingEngine":
        with cls._lock:
            if cls._instance is None:
                cls._instance = AutonomousTradingEngine()
            return cls._instance

    # ─── Strategy Generation ─────────────────────────────────────────────────

    def _generate_strategy(self) -> Optional[GeneratedStrategy]:
        """Use LLM to generate a new trading strategy idea."""
        try:
            from core.llm import route_llm
            llm = route_llm("")
            if not llm:
                return None

            # Get recent market conditions
            market_summary = self._get_market_summary()
            regime_ctx = ""
            sentiment_ctx = ""
            if self.regime_engine:
                candles = self._fetch_klines("BTC-USDT", "1h", 50)
                if candles:
                    r = self.regime_engine.detect(candles, "BTC-USDT")
                    regime_ctx = f"Current regime: {r.get('regime', 'unknown')} (confidence: {r.get('confidence', 0)})."
            if self.sentiment_engine:
                candles = self._fetch_klines("BTC-USDT", "1h", 30)
                if candles:
                    s = self.sentiment_engine.analyze(candles, "BTC-USDT")
                    sentiment_ctx = f"Market sentiment: {s.get('regime', 'neutral')} (score: {s.get('sentiment', 0)})."

            prompt = f"""You are a quantitative trading researcher. Create a novel short-term trading strategy for crypto (BTC/USDT on 1h timeframe).

Current market conditions: {market_summary}
{regime_ctx}
{sentiment_ctx}

Your response must be ONLY a JSON object with these fields:
- name: short catchy name for the strategy
- description: what it does and why it should work (1-2 sentences)
- logic_type: one of [momentum, mean_reversion, breakout, trend_following, volatility]
- params: dict of numeric parameters the strategy needs
- code: Python code string. The code must define a function called `on_data(candles)` that takes a list of candles [[timestamp, open, high, low, close, volume], ...] newest last, and returns exactly "BUY", "SELL", or "HOLD".

**Important:** The runtime provides three helpers you MUST use for parameters:
- `get_int_param(key, default)` — use this for ANY parameter used as a list index, slice, or loop count (e.g., `period = get_int_param("period", 14)`)
- `get_float_param(key, default)` — use this for price thresholds, ratios, or multipliers
- `get_param(key, default)` — generic accessor

Example valid code:
```python
_state = {{}}
def on_data(candles):
    closes = [float(c[4]) for c in candles]
    period = get_int_param("period", 14)
    threshold = get_float_param("threshold", 0.01)
    if len(closes) < period + 1: return "HOLD"
    sma_fast = sum(closes[-get_int_param("fast", 5):]) / get_int_param("fast", 5)
    sma_slow = sum(closes[-period:]) / period
    if sma_fast > sma_slow * (1 + threshold) and _state.get("prev") != "BUY":
        _state["prev"] = "BUY"
        return "BUY"
    if sma_fast < sma_slow * (1 - threshold) and _state.get("prev") != "SELL":
        _state["prev"] = "SELL"
        return "SELL"
    return "HOLD"
```

Be creative. Try something the example didn't do. Return ONLY valid JSON."""

            response = llm.invoke(prompt) if hasattr(llm, "invoke") else llm(prompt)
            if not response or response.startswith("["):
                print("[ATE] LLM error, skipping strategy generation")
                return None

            data = self._extract_json_from_response(response)
            if not data:
                print(f"[ATE] Could not extract valid JSON from LLM response")
                return None

            strategy = GeneratedStrategy(
                name=data.get("name", "Unnamed"),
                description=data.get("description", ""),
                logic_type=data.get("logic_type", "unknown"),
                params=data.get("params", {}),
                code=data.get("code", ""),
                generation_prompt=prompt,
            )
            return strategy
        except Exception as e:
            print(f"[ATE] Strategy generation failed: {e}")
            return None

    def _extract_json_from_response(self, text: str) -> dict | None:
        """Robustly extract JSON from LLM text, handling markdown and partial output."""
        if not text:
            return None

        def _try_parse(candidate: str):
            """Try to parse JSON, with aggressive repair for small-model output."""
            if not candidate:
                return None
            # Strip common LLM artifacts
            candidate = candidate.strip()
            # Strip <thinking> / reasoning tags
            candidate = re.sub(r"<think>.*?</think>", "", candidate, flags=re.DOTALL)
            candidate = re.sub(r"<thinking>.*?</thinking>", "", candidate, flags=re.DOTALL)
            candidate = re.sub(r"\[thinking\].*?\[/thinking\]", "", candidate, flags=re.DOTALL)
            if not candidate:
                return None
            # 1. Direct parse
            try:
                return json.loads(candidate)
            except Exception:
                pass  # expected when LLM returns non-JSON prose
            # 2. Remove trailing commas before } or ]
            repaired = re.sub(r',(\s*[}\]])', r'\1', candidate)
            # 3. Replace single-quoted string keys/values with double quotes (simple cases)
            repaired = re.sub(r"(?<=[{\s,])([a-zA-Z_][a-zA-Z0-9_]*)(?=\s*:)", r'"\1"', repaired)
            try:
                return json.loads(repaired)
            except Exception:
                pass  # repair also failed — expected
            return None

        # 1. Direct parse
        direct = _try_parse(text)
        if direct:
            return direct

        # 2. Markdown code block
        patterns = [
            r'```json\s*([\s\S]*?)\s*```',
            r'```\s*([\s\S]*?)\s*```',
        ]
        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                parsed = _try_parse(match.group(1).strip())
                if parsed:
                    return parsed

        # 3. Find outermost braces by balancing
        brace_depth = 0
        best_start = -1
        best_end = -1
        for i, ch in enumerate(text):
            if ch == '{':
                if brace_depth == 0:
                    best_start = i
                brace_depth += 1
            elif ch == '}':
                brace_depth -= 1
                if brace_depth == 0 and best_start != -1:
                    best_end = i
                    parsed = _try_parse(text[best_start:best_end + 1])
                    if parsed:
                        return parsed

        # 4. Fallback: first-to-last braces
        start = text.find('{')
        end = text.rfind('}')
        if start != -1 and end > start:
            parsed = _try_parse(text[start:end + 1])
            if parsed:
                return parsed

        return None

    def _get_market_summary(self) -> str:
        """Fetch brief market summary for context."""
        try:
            # Binance 24h ticker
            url = "https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT"
            with urllib.request.urlopen(url, timeout=5) as r:
                data = json.loads(r.read())
            change = float(data.get("priceChangePercent", 0))
            vol = float(data.get("volume", 0))
            return f"BTC/USDT 24h change: {change:+.2f}%, volume: {vol:.0f}"
        except Exception:
            return "market data unavailable"

    # ─── Auto-Backtest ───────────────────────────────────────────────────────

    def _auto_backtest(self, strategy: GeneratedStrategy) -> Dict:
        """Run backtest on a generated strategy automatically."""
        executor = StrategyExecutor(strategy)
        if not executor.compile():
            return {"error": "Compilation failed"}

        # Fetch data
        candles = self._fetch_klines("BTC-USDT", "1h", 500)
        if not candles or len(candles) < 50:
            return {"error": "No data"}

        balance = 10000.0
        position = 0.0
        avg_entry = 0.0
        trades = []
        equity = []

        for i in range(30, len(candles)):
            window = candles[:i + 1]
            signal = executor.run(window)
            price = float(window[-1][4])

            if signal == "BUY" and position == 0:
                qty = (balance * 0.95) / price
                fee = qty * price * 0.001
                position = qty
                avg_entry = price
                balance -= qty * price + fee
                trades.append({"side": "BUY", "price": price, "qty": qty, "fee": fee})
            elif signal == "SELL" and position > 0:
                fee = position * price * 0.001
                balance += position * price - fee
                pnl = (price - avg_entry) * position
                trades.append({"side": "SELL", "price": price, "qty": position, "fee": fee, "pnl": pnl})
                position = 0
                avg_entry = 0

            total = balance + (position * price)
            equity.append(total)

        final_price = float(candles[-1][4])
        final_value = balance + (position * final_price)
        ret_pct = ((final_value / 10000) - 1) * 100
        wins = sum(1 for t in trades if t.get("pnl", 0) > 0)
        losses = sum(1 for t in trades if t.get("pnl", 0) < 0)
        total_trades = len([t for t in trades if t["side"] == "SELL"])
        win_rate = (wins / total_trades * 100) if total_trades > 0 else 0

        # Sharpe estimate (simplified)
        if len(equity) > 2:
            returns = [(equity[i] - equity[i-1]) / equity[i-1] for i in range(1, len(equity))]
            mean_ret = sum(returns) / len(returns)
            variance = sum((r - mean_ret) ** 2 for r in returns) / len(returns)
            sharpe = (mean_ret / (variance ** 0.5)) * (252 ** 0.5) if variance > 0 else 0
        else:
            sharpe = 0

        result = {
            "symbol": "BTC-USDT", "interval": "1h", "initial_balance": 10000,
            "final_value": round(final_value, 2), "total_return_pct": round(ret_pct, 2),
            "total_trades": total_trades, "win_rate": round(win_rate, 1),
            "sharpe": round(sharpe, 2), "trades": len(trades),
            "timestamp": datetime.now().isoformat(),
        }

        strategy.backtests.append(result)
        strategy.best_return = max(strategy.best_return, ret_pct)
        strategy.win_rate = win_rate
        strategy.total_trades = total_trades
        strategy.sharpe_estimate = sharpe
        strategy.status = "backtested"

        # Composite score: return * 0.5 + sharpe * 10 + win_rate * 0.2
        strategy.score = (ret_pct * 0.5) + (sharpe * 10) + (win_rate * 0.2)

        return result

    def _fetch_klines(self, symbol: str, interval: str, limit: int) -> List[List]:
        try:
            url = f"https://api.binance.com/api/v3/klines?symbol={symbol.replace('-', '')}&interval={interval}&limit={limit}"
            with urllib.request.urlopen(url, timeout=10) as r:
                return json.loads(r.read())
        except Exception:
            return []

    # ─── Evolution ────────────────────────────────────────────────────────────

    def _evolve_strategies(self):
        """Mutate and combine top strategies to create new ones."""
        if len(self._strategies) < 2:
            return None

        # Sort by score
        sorted_strats = sorted(self._strategies, key=lambda s: s.score, reverse=True)
        top = sorted_strats[:TOP_STRATEGY_COUNT]

        if len(top) < 2:
            return None

        parent1 = random.choice(top)
        parent2 = random.choice(top)

        # Crossover: mix params
        child_params = {}
        for k in set(list(parent1.params.keys()) + list(parent2.params.keys())):
            child_params[k] = parent1.params.get(k, parent2.params.get(k, 10))

        # Mutation: randomize some params by ±20%, preserving int vs float type
        for k in child_params:
            if random.random() < 0.3:
                orig = child_params[k]
                val = float(orig)
                mutated = round(val * random.uniform(0.8, 1.2), 2)
                # Preserve integer type if the original was a whole-number int
                if isinstance(orig, int) or (isinstance(orig, float) and orig.is_integer()):
                    child_params[k] = int(mutated)
                else:
                    child_params[k] = mutated

        child = GeneratedStrategy(
            name=f"Evolved_{parent1.name[:10]}_{parent2.name[:10]}",
            description=f"Evolved from {parent1.name} and {parent2.name}. Mutated params.",
            logic_type=random.choice([parent1.logic_type, parent2.logic_type]),
            params=child_params,
            code=parent1.code,  # Inherit code from better parent
            generation_prompt=f"Evolution of {parent1.id} x {parent2.id}",
        )

        # Backtest the child immediately
        result = self._auto_backtest(child)
        if "error" not in result:
            self._strategies.append(child)
            self._log_evolution(parent1, parent2, child, result)
            return child
        return None

    def _log_evolution(self, p1, p2, child, result):
        try:
            entry = {
                "timestamp": datetime.now().isoformat(),
                "parent1": p1.id, "parent2": p2.id,
                "child": child.id, "child_score": child.score,
                "result": result,
            }
            with open(STRATEGY_EVOLUTION_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry) + "\n")
        except Exception as e:
            from core.execution_guard import log_error
            log_error(e, module="core.autonomous_trading_engine")

    # ─── Auto Paper Trade ────────────────────────────────────────────────────

    def _auto_paper_trade(self):
        """Run the top strategy in paper trading mode automatically."""
        if not self._auto_trade_enabled:
            return
        active = [s for s in self._strategies if s.status in ("backtested", "active") and s.score > 0]
        if not active:
            return

        top = max(active, key=lambda s: s.score)
        executor = StrategyExecutor(top)

        # Get recent candles
        candles = self._fetch_klines("BTC-USDT", "1h", 50)
        if not candles:
            return

        signal = executor.run(candles)
        if signal == "HOLD":
            return

        # Execute via paper engine
        try:
            from core.finance_guardian import get_finance_guardian
            guardian = get_finance_guardian()
            price_data = guardian.get_market_price("BTC-USDT")
            price = None
            if "error" not in price_data:
                pdata = price_data.get("data", price_data)
                price = float(pdata.get("lastPrice", pdata.get("price", 0)))

            # Risk-managed position sizing
            qty = 0.001
            if self.risk_engine and price:
                # Simple ATR-based stop loss for sizing
                candles = self._fetch_klines("BTC-USDT", "1h", 20)
                if candles and len(candles) >= 10:
                    atr = sum(float(c[2]) - float(c[3]) for c in candles[-10:]) / 10
                    sl = price - (atr * 2) if signal == "BUY" else price + (atr * 2)
                    sizing = self.risk_engine.position_size(price, sl, "BTC-USDT")
                    qty = sizing.get("quantity", 0.001)
                    if qty <= 0:
                        print(f"[ATE] Risk manager blocked {signal} BTC-USDT")
                        return

            # Quant signal overlay: only trade if quant ensemble agrees
            if self.quant_engine:
                candles = self._fetch_klines("BTC-USDT", "1h", 100)
                regime_hint = None
                if self.regime_engine:
                    r = self.regime_engine.detect(candles, "BTC-USDT")
                    regime_hint = r.get("regime", "").lower()
                q = self.quant_engine.analyze(candles, "BTC-USDT", regime_hint=regime_hint)
                q_sig = q.get("signal", "HOLD")
                if q_sig != signal and q.get("confidence", 0) > 0.5:
                    print(f"[ATE] Quant overlay override: {signal} -> HOLD (quant says {q_sig})")
                    return
                elif q_sig == signal:
                    print(f"[ATE] Quant overlay confirms {signal}")

            result = guardian.place_trade("BTC-USDT", signal, qty, paper=True)

            if result.get("success"):
                top.paper_trades.append({
                    "side": signal, "qty": qty, "price": price,
                    "timestamp": datetime.now().isoformat(),
                    "result": result,
                })
                # Record P&L for risk manager Kelly tracking
                if self.risk_engine and result.get("order"):
                    order = result["order"]
                    pnl = order.get("pnl", 0)
                    at_risk = order.get("total", qty * price) if price else qty * 30000
                    self.risk_engine.record_trade_pnl(pnl, at_risk)
                top.status = "active"
                self._save_strategies()

                # Push to user
                if PUSH_AVAILABLE:
                    try:
                        get_push_engine().push(
                            "INSIGHT",
                            f"🧪 Auto-paper-trade: {signal} {qty} BTC-USDT via strategy '{top.name}' (score: {top.score:.1f})",
                            priority="normal",
                            metadata={"source": "autonomous_trading", "strategy": top.id},
                        )
                    except Exception as e:
                        from core.execution_guard import log_error
                        log_error(e, module="core.autonomous_trading_engine")

                # Log
                try:
                    with open(AUTO_TRADE_LOG, "a", encoding="utf-8") as f:
                        f.write(json.dumps({
                            "timestamp": datetime.now().isoformat(),
                            "strategy_id": top.id, "signal": signal,
                            "qty": qty, "price": price,
                        }) + "\n")
                except Exception as e:
                    from core.execution_guard import log_error
                    log_error(e, module="core.autonomous_trading_engine")
        except Exception as e:
            print(f"[ATE] Auto paper trade error: {e}")

    # ─── Auto Collection from All Sources ────────────────────────────────────

    def _auto_collect(self):
        """Trigger collection from all connected sources periodically."""
        try:
            from core.finance_guardian import get_finance_guardian
            guardian = get_finance_guardian()

            # This is a hook; actual collection happens via:
            # 1. Notification ingestion engine routing finance notifs to guardian
            # 2. Email/webhook endpoints being called
            # 3. Exchange balance sync
            # We just log that auto-collection is alive
            pass
        except Exception as e:
            print(f"[ATE] Auto collect check: {e}")

    # ─── Main Loop ───────────────────────────────────────────────────────────

    def start(self):
        if self._running:
            return
        self._running = True

        t1 = threading.Thread(target=self._generation_loop, daemon=True, name="ATE-Generate")
        t2 = threading.Thread(target=self._paper_trade_loop, daemon=True, name="ATE-PaperTrade")
        self._threads = [t1, t2]
        for t in self._threads:
            t.start()
        print("[AutonomousTradingEngine] Started. Will generate strategies, backtest, and paper-trade autonomously.")

    def stop(self):
        self._running = False
        self._save_strategies()

    def _generation_loop(self):
        """Generate new strategies and evolve existing ones."""
        time.sleep(60)  # Let system settle
        while self._running:
            try:
                now = time.time()
                if now - self._last_generate_time > AUTO_GENERATE_INTERVAL * 60:
                    self._last_generate_time = now

                    # Generate new strategy
                    strategy = self._generate_strategy()
                    if strategy:
                        result = self._auto_backtest(strategy)
                        if "error" not in result:
                            self._strategies.append(strategy)
                            self._save_strategies()
                            print(f"[ATE] Generated strategy '{strategy.name}' — return: {result['total_return_pct']:.1f}%, trades: {result['total_trades']}, win_rate: {result['win_rate']:.1f}%")

                            # Push to user if it's good
                            if result["total_return_pct"] > 5 and PUSH_AVAILABLE:
                                try:
                                    get_push_engine().push(
                                        "INSIGHT",
                                        f"🧠 New trading idea: '{strategy.name}' backtested at +{result['total_return_pct']:.1f}% return. Strategy: {strategy.description[:80]}",
                                        priority="normal",
                                        metadata={"source": "autonomous_trading", "strategy": strategy.id},
                                    )
                                except Exception as e:
                                    from core.execution_guard import log_error
                                    log_error(e, module="core.autonomous_trading_engine")

                    # Evolve existing
                    if len(self._strategies) >= 3:
                        evolved = self._evolve_strategies()
                        if evolved:
                            print(f"[ATE] Evolved strategy '{evolved.name}' — score: {evolved.score:.1f}")

                time.sleep(60)
            except Exception as e:
                print(f"[ATE] Generation loop error: {e}")
                time.sleep(300)

    def _paper_trade_loop(self):
        """Run top strategy in paper trading."""
        time.sleep(120)
        while self._running:
            try:
                now = time.time()
                if now - self._last_paper_trade_time > AUTO_PAPER_TRADE_INTERVAL * 60:
                    self._last_paper_trade_time = now
                    self._auto_paper_trade()
                time.sleep(60)
            except Exception as e:
                print(f"[ATE] Paper trade loop error: {e}")
                time.sleep(300)

    # ─── Persistence ─────────────────────────────────────────────────────────

    def _save_strategies(self):
        try:
            data = [s.to_dict() for s in self._strategies]
            GENERATED_STRATEGIES_DB.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except Exception as e:
            from core.execution_guard import log_error
            log_error(e, module="core.autonomous_trading_engine")

    def _load_strategies(self):
        if not GENERATED_STRATEGIES_DB.exists():
            return
        try:
            data = json.loads(GENERATED_STRATEGIES_DB.read_text(encoding="utf-8"))
            for s in data:
                try:
                    self._strategies.append(GeneratedStrategy.from_dict(s))
                except Exception as e:
                    from core.execution_guard import log_error
                    log_error(e, module="core.autonomous_trading_engine")
        except Exception as e:
            from core.execution_guard import log_error
            log_error(e, module="core.autonomous_trading_engine")

    # ─── Public API ──────────────────────────────────────────────────────────

    def get_strategies(self) -> List[Dict]:
        return [s.to_dict() for s in reversed(self._strategies)]

    def get_top_strategy(self) -> Optional[Dict]:
        active = [s for s in self._strategies if s.score > 0]
        if not active:
            return None
        return max(active, key=lambda s: s.score).to_dict()

    def get_evolution_log(self, limit: int = 20) -> List[Dict]:
        if not STRATEGY_EVOLUTION_LOG.exists():
            return []
        try:
            lines = STRATEGY_EVOLUTION_LOG.read_text(encoding="utf-8").strip().split("\n")
            return [json.loads(line) for line in lines[-limit:] if line.strip()]
        except Exception:
            return []

    def get_auto_trade_log(self, limit: int = 20) -> List[Dict]:
        if not AUTO_TRADE_LOG.exists():
            return []
        try:
            lines = AUTO_TRADE_LOG.read_text(encoding="utf-8").strip().split("\n")
            return [json.loads(line) for line in lines[-limit:] if line.strip()]
        except Exception:
            return []

    def force_generate(self) -> Dict:
        """Manually trigger strategy generation."""
        strategy = self._generate_strategy()
        if not strategy:
            return {"success": False, "error": "Generation failed"}
        result = self._auto_backtest(strategy)
        if "error" in result:
            return {"success": False, "error": result["error"]}
        self._strategies.append(strategy)
        self._save_strategies()
        return {"success": True, "strategy": strategy.to_dict(), "backtest": result}

    def force_paper_trade(self) -> Dict:
        """Manually trigger auto paper trade."""
        self._auto_paper_trade()
        return {"success": True, "message": "Auto paper trade executed"}

    def get_status(self) -> Dict:
        return {
            "running": self._running,
            "strategies_generated": len(self._strategies),
            "last_generate_minutes_ago": round((time.time() - self._last_generate_time) / 60, 1),
            "last_paper_trade_minutes_ago": round((time.time() - self._last_paper_trade_time) / 60, 1),
            "top_strategy": self.get_top_strategy(),
        }


# ─── Singleton ────────────────────────────────────────────────────────────

def get_autonomous_trading_engine() -> AutonomousTradingEngine:
    return AutonomousTradingEngine.get_instance()


def start_autonomous_trading_engine():
    engine = get_autonomous_trading_engine()
    engine.start()
    return engine


def stop_autonomous_trading_engine():
    engine = get_autonomous_trading_engine()
    engine.stop()