"""
LOVE Daily Briefing System

Every morning at a configured time (default 08:00), LOVE assembles a rich
briefing from ALL connected sources and delivers it as a proactive notification.

Sources aggregated:
  - Google Calendar: today's events, free slots
  - Outlook/Teams: unread emails, calendar, presence
  - Finance: BTC/ETH prices, any overnight moves
  - GitHub: notifications, PR activity
  - System: battery, active process
  - Goals: active goals, recent progress
  - Memory: anything important from yesterday

The brief is generated by the LLM in LOVE's warm/direct voice — not a generic
dashboard dump. Each section ends with a proactive suggestion.
"""

import json
import threading
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

DATA_DIR = Path(__file__).parent.parent / "data"
BRIEF_LOG = DATA_DIR / "daily_briefs.jsonl"
BRIEF_STATE_FILE = DATA_DIR / "daily_brief_state.json"
DATA_DIR.mkdir(parents=True, exist_ok=True)

DEFAULT_BRIEF_TIME = "08:00"  # HH:MM local time


class DailyBriefingSystem:
    """
    Generates and schedules the LOVE morning brief.
    Singleton — call DailyBriefingSystem.get_instance()
    """

    _instance: Optional["DailyBriefingSystem"] = None
    _lock = threading.Lock()

    def __init__(self):
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_brief: Optional[Dict] = None
        self._last_brief_date: Optional[str] = None
        self._brief_time: str = DEFAULT_BRIEF_TIME
        self._load_state()

    @classmethod
    def get_instance(cls) -> "DailyBriefingSystem":
        with cls._lock:
            if cls._instance is None:
                cls._instance = DailyBriefingSystem()
            return cls._instance

    # ── State persistence ─────────────────────────────────────────────────────

    def _load_state(self):
        try:
            if BRIEF_STATE_FILE.exists():
                state = json.loads(BRIEF_STATE_FILE.read_text())
                self._last_brief = state.get("last_brief")
                self._last_brief_date = state.get("last_brief_date")
                self._brief_time = state.get("brief_time", DEFAULT_BRIEF_TIME)
        except Exception:
            pass

    def _save_state(self):
        try:
            BRIEF_STATE_FILE.write_text(json.dumps({
                "last_brief": self._last_brief,
                "last_brief_date": self._last_brief_date,
                "brief_time": self._brief_time,
            }, indent=2, default=str))
        except Exception:
            pass

    # ── Data gathering ────────────────────────────────────────────────────────

    def _gather_data(self) -> Dict[str, Any]:
        """Pull data from all connected sources."""
        data: Dict[str, Any] = {
            "date": datetime.now().strftime("%A, %B %d, %Y"),
            "time": datetime.now().strftime("%I:%M %p"),
        }

        # Google Calendar
        try:
            from integrations.google_services import GoogleServices
            gs = GoogleServices.get_instance()
            if gs.is_connected():
                events = gs.get_todays_events()
                data["google_events"] = events
                data["google_event_count"] = len(events)
                insights = gs.get_calendar_insights()
                data["google_insights"] = insights
                email = gs.get_email_summary()
                data["gmail_unread"] = email.get("unread_important", 0)
                data["gmail_urgent"] = email.get("urgent", [])[:3]
        except Exception:
            pass

        # Microsoft
        try:
            from integrations.microsoft_bridge import MicrosoftBridge
            ms = MicrosoftBridge.get_instance()
            if ms.is_connected():
                data["ms_unread"] = ms.get_unread_count()
                data["ms_events"] = ms.get_todays_events()
                data["ms_next_event"] = ms.get_next_event()
                data["ms_presence"] = ms.get_my_presence()
        except Exception:
            pass

        # Finance
        try:
            from integrations.finance_intelligence import get_finance_intelligence
            fi = get_finance_intelligence()
            prices = fi.get_prices()
            data["finance_prices"] = {k: {"price": v.get("price"), "change_pct": v.get("change_pct")}
                                      for k, v in prices.items()}
            data["finance_alerts"] = fi.get_alerts(5)
            data["finance_summary"] = fi.get_price_summary()
        except Exception:
            pass

        # GitHub
        try:
            from integrations.github_monitor import get_github_monitor
            gh = get_github_monitor()
            if gh.is_connected():
                notifs = gh.get_notifications(10)
                data["github_notifications"] = len(notifs)
                data["github_recent"] = gh.get_recent_events(3)
        except Exception:
            pass

        # Goals
        try:
            from core.autonomous_goal_engine import get_goal_status
            status = get_goal_status()
            data["goals"] = status.get("goals", [])[:5]
            data["goals_active"] = status.get("active_count", 0)
        except Exception:
            pass

        # System awareness
        try:
            from core.awareness import get_full_snapshot
            snap = get_full_snapshot()
            data["system_battery"] = snap.get("battery_percent")
            data["system_cpu"] = snap.get("cpu_percent")
        except Exception:
            pass

        # Yesterday memory recall
        try:
            from core.memory import recall_memory
            yesterday_str = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
            mem = recall_memory(f"what happened on {yesterday_str}", limit=3)
            data["yesterday_memory"] = str(mem)[:500] if mem else ""
        except Exception:
            pass


        # Life Domains -- hydration, sleep, nutrition, skincare
        try:
            from core.life_domains import get_life_domains_engine
            engine = get_life_domains_engine()
            dash = engine.get_dashboard()
            data["life_score"] = dash.get("life_score", 0)
            data["life_nudges"] = dash.get("nudges", [])
            data["life_hydration_pct"] = dash.get("hydration", {}).get("pct", 0)
            data["life_sleep_hours"] = dash.get("sleep", {}).get("hours", 0)
            data["life_sleep_quality"] = dash.get("sleep", {}).get("quality", 0)
            data["life_meals_logged"] = dash.get("nutrition", {}).get("meal_count", 0)
            data["life_skincare_done"] = dash.get("skincare", {}).get("daily_score", 0)
            data["life_streaks"] = engine.get_streaks()
        except Exception:
            pass

        # Cross-domain correlations
        try:
            from core.cross_domain_intelligence import get_correlations
            data["cross_domain_insights"] = get_correlations()
        except Exception:
            pass

        # Evolution activity (overnight self-improvement)
        try:
            from core.evolution_integration import get_evolution_integration
            evo = get_evolution_integration()
            stats = evo.get_integration_status().get("statistics", {})
            data["evo_code_mods"] = stats.get("total_code_modifications", 0)
            data["evo_mutations"] = stats.get("total_mutations_applied", 0)
            data["evo_adoptions"] = stats.get("successful_cross_adoptions", 0)
        except Exception:
            pass

        # Modern AI module status
        try:
            from core.agi_spine import get_agi_flags
            flags = get_agi_flags()
            modern_modules = [
                "llm_manager", "graph_rag", "prompt_optimizer", "self_reflection",
                "conversation_quality", "predictive_maintenance", "multi_agent_orchestrator",
                "intent_predictor", "personality_adapter", "response_cache",
                "context_window_manager", "user_pattern_detector", "goal_drift_detector",
                "cross_modal_fusion", "emotional_resonance", "knowledge_graph_builder",
                "adaptive_learning_rate", "conversation_continuity",
                "memory_compressor", "semantic_search_optimizer",
                "emotion_aware_response", "knowledge_injector",
                "habit_streak_tracker", "sleep_analyzer",
                "social_connection_monitor", "learning_path_optimizer",
                "focus_recovery_tracker", "decision_journal",
                "mood_journal", "values_alignment_checker",
                "gratitude_tracker", "energy_audit_tool",
                "time_audit_tool", "reflection_prompt_generator",
                "proactive_preparation_engine", "context_switching_minimizer",
                "task_batch_optimizer", "meeting_optimizer",
                "finance_pattern_detector", "nutrition_analyzer",
                "exercise_optimizer", "meditation_coach",
                "reading_tracker", "writing_coach",
                "creativity_booster", "stress_response_coach",
                "communication_analyzer", "goal_progress_visualizer",
                "life_balance_wheel", "productivity_gamifier",
                "environment_optimizer", "weather_suggester",
                "travel_planner", "gift_idea_generator",
                "emergency_preparedness_tracker", "home_maintenance_scheduler",
                "career_path_mapper", "skill_gap_analyzer",
                "document_organizer", "password_health_checker",
                "subscription_manager", "digital_declutterer",
                "event_planner", "habit_builder",
                "morning_routine_designer", "evening_wind_down_coach",
                "conflict_resolution_coach", "boundaries_coach",
                "assertiveness_trainer", "active_listening_coach",
                "self_compassion_coach", "forgiveness_tracker",
                "vulnerability_builder", "trust_builder",
                "curiosity_spark", "play_coach",
                "adventure_planner", "wonder_tracker",
                "meaning_mapper", "purpose_navigator",
                "legacy_builder", "death_awareness_coach",
                "flow_state_coach", "savoring_trainer",
                "presence_detector", "intuition_trainer",
                "resilience_builder", "growth_mindset_coach",
                "adaptability_trainer", "antifragility_tracker",
                "discipline_trainer", "consistency_coach",
                "accountability_partner", "progress_celebrator",
                "energy_protector", "boundary_enforcer",
                "time_sovereign", "attention_guardian",
                "identity_designer", "habit_architect",
                "environment_curator", "ritual_master",
                "values_explorer", "belief_examiner",
                "shadow_integrator", "inner_critic_manager",
                "emotional_intelligence_trainer", "empathy_builder",
                "compassion_generator", "gratitude_amplifier",
                "deep_work_enabler", "recovery_optimizer",
                "peak_performance_tracker", "mindful_productivity_coach",
                "sleep_optimizer", "nutrition_coach",
                "movement_tracker", "health_integrator",
                "digital_minimalism_coach", "focus_ritual_designer",
                "attention_recovery_specialist", "cognitive_load_manager",
                "stress_resilience_trainer", "emotional_regulation_coach",
                "mindfulness_trainer", "presence_amplifier",
                "creativity_catalyst", "innovation_spark_generator",
                "problem_reframer", "perspective_shifter",
                "curiosity_cultivator", "learning_acceleration_engine",
                "knowledge_synthesizer", "wisdom_distiller",
                "purpose_clarity_engine", "legacy_builder",
                "impact_maximizer", "meaning_amplifier",
                "courage_coach", "risk_intelligence_trainer",
                "vulnerability_builder", "authenticity_amplifier",
                "humor_playfulness_trainer", "joy_cultivator",
                "celebration_architect", "spontaneity_generator",
                "forgiveness_coach", "reconciliation_builder",
                "trust_architect", "repair_specialist",
                "deep_listener", "conflict_navigator",
                "assertiveness_builder", "boundary_architect",
                "leadership_coach", "influence_builder",
                "delegation_trainer", "vision_keeper",
                "investment_strategist", "wealth_builder",
                "income_diversifier", "financial_independence_tracker",
                "sustainability_coach", "nature_connector",
                "eco_footprint_tracker", "regenerative_living_guide",
                "spiritual_practice_coach", "transcendence_guide",
                "sacred_ritual_designer", "contemplation_keeper",
                "experience_maximizer", "wonder_cultivator",
                "travel_optimizer",
                "community_builder", "social_impact_tracker",
                "volunteer_coordinator", "network_weaver",
                "longevity_optimizer", "vitality_tracker",
                "age_reversal_coach", "life_phase_navigator",
                "parenting_coach", "family_harmony_builder",
                "grief_support_companion", "humor_cultivator",
                "civic_engagement_tracker", "mentorship_weaver",
                "wisdom_keeper", "play_architect",
                "home_environment_optimizer", "intergenerational_bridge_builder",
                "aesthetic_life_designer", "comfort_zone_challenger",
                "conflict_resolution_coach", "forgiveness_facilitator",
                "celebration_architect", "rest_designer",
                "boundary_coach", "emotional_literacy_trainer",
                "hope_cultivator", "attention_steward",
                "identity_explorer", "values_navigator",
                "belonging_builder", "rejection_resilience_coach",
                "storytelling_coach", "voice_finder",
                "transition_companion", "uncertainty_embracer",
                "experience_maximizer", "wonder_cultivator",
                "travel_optimizer",
                "community_builder", "social_impact_tracker",
                "volunteer_coordinator", "network_weaver",
                "longevity_optimizer", "vitality_tracker",
                "age_reversal_coach", "life_phase_navigator",
                "parenting_coach", "family_harmony_builder",
                "grief_support_companion", "humor_cultivator",
                "civic_engagement_tracker", "mentorship_weaver",
                "wisdom_keeper", "play_architect",
                "home_environment_optimizer", "intergenerational_bridge_builder",
                "aesthetic_life_designer", "comfort_zone_challenger",
                "boundary_coach", "emotional_literacy_trainer",
                "hope_cultivator", "attention_steward",
                "identity_explorer", "values_navigator",
                "belonging_builder", "rejection_resilience_coach",
                "storytelling_coach", "voice_finder",
                "transition_companion", "uncertainty_embracer",
            ]
            active_modern = [m for m in modern_modules if flags.get(m, False)]
            data["modern_modules_active"] = len(active_modern)
            data["modern_modules_total"] = len(modern_modules)
            data["modern_modules"] = active_modern
        except Exception:
            data["modern_modules_active"] = 0
            data["modern_modules_total"] = 23

        # Emotional trajectory summary
        try:
            from core.emotion_aware_response import get_emotion_aware_response_generator
            ear = get_emotion_aware_response_generator()
            traj = ear.get_emotional_trajectory()
            data["emotion_trend"] = traj.get("trend", "unknown")
            data["emotion_recent_avg"] = traj.get("recent_avg", 0)
        except Exception:
            pass

        # Predictive maintenance alerts
        try:
            from core.predictive_maintenance import get_predictive_maintenance_engine
            pme = get_predictive_maintenance_engine()
            predictions = pme.get_predictions()
            data["predictive_alerts"] = len([p for p in predictions if p.get("severity") == "high"])
        except Exception:
            pass

        # Goal drift detection
        try:
            from core.goal_drift_detector import get_goal_drift_detector
            gdd = get_goal_drift_detector()
            alerts = gdd.get_drift_alerts()
            data["goal_drift_alerts"] = len(alerts)
        except Exception:
            pass

        return data

    # ── Brief generation ──────────────────────────────────────────────────────

    def generate_brief(self, force: bool = False) -> Dict[str, Any]:
        """
        Generate today's brief. Returns the brief dict.
        If already generated today and force=False, returns cached version.
        """
        today = datetime.now().strftime("%Y-%m-%d")
        if not force and self._last_brief_date == today and self._last_brief:
            return {**self._last_brief, "cached": True}

        data = self._gather_data()
        brief_text = self._generate_text(data)

        brief = {
            "date": today,
            "generated_at": datetime.now().isoformat(),
            "text": brief_text,
            "data": _strip_non_serializable(data),
            "cached": False,
        }

        self._last_brief = brief
        self._last_brief_date = today
        self._save_state()

        # Log
        try:
            with open(BRIEF_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps({"date": today, "text": brief_text}, ensure_ascii=False) + "\n")
        except Exception:
            pass

        # Push as notification
        try:
            from core.proactive_push import get_push_engine
            preview = brief_text[:200].replace("\n", " ")
            get_push_engine().push(
                "Morning Brief",
                preview + "...",
                priority="high",
                metadata={"type": "morning_brief"},
            )
        except Exception:
            pass

        # Publish to neural bus
        try:
            from core.neural_bus import get_neural_bus
            get_neural_bus().publish(
                event_type="daily_brief_generated",
                domain="briefing",
                payload={"date": today, "preview": brief_text[:100]},
            )
        except Exception:
            pass

        return brief

    def _generate_text(self, data: Dict[str, Any]) -> str:
        """Use the LLM to generate the brief in LOVE's voice."""
        sections = _build_raw_sections(data)
        if not sections:
            return f"Good morning. Quiet day ahead on {data.get('date', 'today')}. Nothing critical in any of your connected sources."

        prompt = _build_brief_prompt(data, sections)

        try:
            from core.llm import get_reasoning_llm
            llm = get_reasoning_llm()
            raw = str(llm.invoke(prompt))

            # Strip <think> tags from reasoning models
            import re
            raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
            return raw if raw else _fallback_brief(data, sections)
        except Exception as e:
            return _fallback_brief(data, sections)

    # ── Scheduler ────────────────────────────────────────────────────────────

    def set_brief_time(self, time_str: str):
        """Set the daily brief time. Format: HH:MM (24h)."""
        self._brief_time = time_str
        self._save_state()

    def start(self, brief_time: Optional[str] = None):
        """Start the daily briefing daemon."""
        if brief_time:
            self._brief_time = brief_time
        if self._running:
            return
        self._running = True

        def _loop():
            while self._running:
                try:
                    now = datetime.now()
                    h, m = map(int, self._brief_time.split(":"))
                    target = now.replace(hour=h, minute=m, second=0, microsecond=0)
                    if now >= target:
                        target += timedelta(days=1)
                    wait_secs = (target - now).total_seconds()
                    print(f"[DailyBrief] Next brief at {target.strftime('%H:%M')} ({wait_secs/3600:.1f}h away)")

                    # Sleep in 60s chunks so we can stop cleanly
                    slept = 0
                    while self._running and slept < wait_secs:
                        time.sleep(min(60, wait_secs - slept))
                        slept += 60

                    if self._running:
                        print("[DailyBrief] Generating morning brief...")
                        self.generate_brief(force=True)
                except Exception as e:
                    print(f"[DailyBrief] Scheduler error: {e}")
                    time.sleep(300)

        self._thread = threading.Thread(target=_loop, daemon=True, name="LOVE-DailyBrief")
        self._thread.start()
        print(f"[DailyBrief] Started — daily brief scheduled at {self._brief_time}")

    def stop(self):
        self._running = False

    def get_status(self) -> Dict[str, Any]:
        return {
            "running": self._running,
            "brief_time": self._brief_time,
            "last_brief_date": self._last_brief_date,
            "last_brief_preview": (self._last_brief or {}).get("text", "")[:200] if self._last_brief else None,
        }

    def get_last_brief(self) -> Optional[Dict]:
        return self._last_brief


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_raw_sections(data: Dict) -> List[str]:
    sections = []

    # Google Calendar
    events = data.get("google_events", [])
    if events:
        count = len(events)
        sections.append(f"CALENDAR: {count} events today")
        for ev in events[:3]:
            mins = ev.get("minutes_away")
            when = f" (in {mins}min)" if mins and mins > 0 else ""
            sections.append(f"  - {ev.get('start_str','')} {ev.get('title','')}{when}")
        insights = data.get("google_insights", {})
        if insights.get("free_slots"):
            sections.append(f"  Free slots: {', '.join(insights['free_slots'][:2])}")
    elif data.get("ms_events"):
        events = data["ms_events"]
        sections.append(f"CALENDAR: {len(events)} Outlook events today")
        for ev in events[:3]:
            start = ev.get("start_str", ev.get("start", ""))[:16].replace("T", " ")
            mins = ev.get("minutes_away")
            when = f" (in {mins}min)" if mins and mins > 0 else ""
            sections.append(f"  - {start} {ev.get('title','')}{when}")

    # Email
    gmail_unread = data.get("gmail_unread", 0)
    ms_unread = data.get("ms_unread", 0)
    if gmail_unread or ms_unread:
        email_parts = []
        if gmail_unread:
            email_parts.append(f"{gmail_unread} important Gmail")
        if ms_unread:
            email_parts.append(f"{ms_unread} Outlook unread")
        sections.append(f"EMAIL: {', '.join(email_parts)}")
        for urgent in data.get("gmail_urgent", [])[:2]:
            sections.append(f"  - [{urgent.get('from','')[:25]}] {urgent.get('subject','')[:50]}")

    # Finance
    prices = data.get("finance_prices", {})
    if prices:
        price_strs = []
        for sym, p in list(prices.items())[:4]:
            pct = p.get("change_pct")
            pct_str = f" ({'+' if pct and pct > 0 else ''}{pct:.1f}%)" if pct is not None else ""
            price_strs.append(f"{sym} ${p.get('price', '?')}{pct_str}")
        sections.append("FINANCE: " + " | ".join(price_strs))
        for alert in data.get("finance_alerts", [])[:2]:
            if alert.get("severity") in ("high", "critical"):
                sections.append(f"  ! {alert.get('message','')[:80]}")

    # GitHub
    notifs = data.get("github_notifications", 0)
    if notifs:
        sections.append(f"GITHUB: {notifs} unread notifications")
        for ev in data.get("github_recent", [])[:2]:
            sections.append(f"  - {ev.get('summary', '')[:70]}")

    # Goals
    goals = data.get("goals", [])
    active = data.get("goals_active", 0)
    if goals:
        sections.append(f"GOALS: {active} active goals")
        for g in goals[:3]:
            prog = g.get("progress", 0)
            sections.append(f"  - {g.get('title','')[:40]} ({prog}%)")

    # Life Domains (body tracking)
    life_score = data.get("life_score", 0)
    if life_score > 0 or data.get("life_nudges"):
        parts = [f"Life score: {life_score:.0f}/100"]
        sleep_h = data.get("life_sleep_hours", 0)
        if sleep_h:
            parts.append(f"Sleep: {sleep_h}h (quality {data.get('life_sleep_quality', '?')}/10)")
        hydra = data.get("life_hydration_pct", 0)
        if hydra:
            parts.append(f"Hydration: {hydra:.0f}%")
        meals = data.get("life_meals_logged", 0)
        parts.append(f"Meals: {meals}/3")
        skincare = data.get("life_skincare_done", 0)
        if skincare:
            parts.append(f"Skincare: {skincare:.0f}%")
        sections.append("BODY: " + " | ".join(parts))
        streaks = data.get("life_streaks", {})
        streak_parts = [f"{k}: {v}d" for k, v in streaks.items() if v > 0]
        if streak_parts:
            sections.append(f"  Streaks: {', '.join(streak_parts)}")
        for nudge in data.get("life_nudges", [])[:2]:
            sections.append(f"  > {nudge}")

    # Cross-domain insights
    xd = data.get("cross_domain_insights")
    if xd and isinstance(xd, dict):
        correlations = xd.get("correlations", [])
        for c in correlations[:2]:
            sections.append(f"  PATTERN: {c}")

    # System
    bat = data.get("system_battery")
    if bat is not None and bat < 30:
        sections.append(f"SYSTEM: Battery low at {bat}%")


    # Evolution activity (overnight self-improvement)
    evo_mods = data.get("evo_code_mods", 0)
    evo_muts = data.get("evo_mutations", 0)
    evo_adopts = data.get("evo_adoptions", 0)
    if evo_mods > 0 or evo_muts > 0 or evo_adopts > 0:
        parts = []
        if evo_mods > 0:
            parts.append(f"{evo_mods} code mod(s)")
        if evo_muts > 0:
            parts.append(f"{evo_muts} mutation(s)")
        if evo_adopts > 0:
            parts.append(f"{evo_adopts} peer adoption(s)")
        joined = " | ".join(parts)
        sections.append(f"EVOLUTION: Overnight I applied {joined}.")

    return sections


def _build_brief_prompt(data: Dict, sections: List[str]) -> str:
    raw = "\n".join(sections)
    name = "Karthi"
    hour = datetime.now().hour
    greeting = "Good morning" if 5 <= hour < 12 else "Good afternoon" if hour < 17 else "Good evening"
    return f"""You are LOVE, {name}'s autonomous AI companion. Generate a morning brief.

Today: {data.get('date', '')}

RAW DATA:
{raw}

INSTRUCTIONS:
- Write like you know {name} personally, not like a dashboard report
- Lead with what matters most (meetings, urgent emails, market moves)
- Be specific about times and names
- Include 1-2 sharp proactive suggestions (what should {name} do first?)
- Keep it under 200 words
- No generic phrases like "Have a great day!" — be direct and specific
- No bullet points or headers, just flowing natural language
- End with one clear "first thing to do" suggestion

Write the brief now:"""


def _fallback_brief(data: Dict, sections: List[str]) -> str:
    """Plain text fallback if LLM fails."""
    date = data.get("date", datetime.now().strftime("%A, %B %d, %Y"))
    lines = [f"Morning brief for {date}:", ""]
    lines.extend(sections)
    return "\n".join(lines)


def _strip_non_serializable(d: Dict) -> Dict:
    """Remove datetime objects and other non-JSON-serializable values."""
    import copy
    result = {}
    for k, v in d.items():
        try:
            json.dumps(v)
            result[k] = v
        except (TypeError, ValueError):
            result[k] = str(v)[:200]
    return result


# ── Singleton accessor ────────────────────────────────────────────────────────

def get_briefing_system() -> DailyBriefingSystem:
    return DailyBriefingSystem.get_instance()
